name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Cloud Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev libssl-dev build-essential ffmpeg openjdk-17-jdk unzip zip ccache

    - name: Install Compatible Build Tools
      run: |
        pip install --upgrade pip
        pip install "setuptools<66.0.0" "cython>=0.29.33,<3.0.0" wheel
        pip install git+https://github.com/kivy/buildozer.git@master

    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug
